apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fluentd
bases:
- ../../base
patchesStrategicMerge:
- patches.yaml
secretGenerator:
- name: fluentd-juicefs
  env: secret.env
images:
- name: juicedata/fluentd-juicefs
  newTag: dev
