apiVersion: v1
kind: Secret
metadata:
  name: fluentd-juicefs
  namespace: default
type: Opaque
stringData:
  JFS_NAME: "<Name of your JuiceFS created in https://juicefs.com/console/create>"
  JFS_TOKEN: "<Token for JuiceFS access in https://juicefs.com/console/vol/:name/settings>"
  JFS_ACCESSKEY: "<Access key ID for object storage>"
  JFS_SECRETKEY: "<Secret access key for object storage>"
